export const state = {
    records: [],
    schulte: {
      size: 5,
      showSelected: true,
      board: [],
      next: 1,
      startTime: null,
      timerId: null,
      finished: false,
      wrongValue: null
    },
    tback: {
      level: 2,
      rounds: 24,
      interval: 1800,
      sequence: [],
      currentIndex: -1,
      timerId: null,
      stepStartedAt: 0,
      active: false,
      pressedIndices: new Set(),
      hits: 0,
      misses: 0,
      falseAlarms: 0,
      targets: 0,
      durationMs: 0
    },
    stroop: {
      rounds: 24,
      trials: [],
      currentIndex: -1,
      currentTrial: null,
      optionOrder: [],
      active: false,
      locked: false,
      startTime: 0,
      trialStartedAt: 0,
      correct: 0,
      wrong: 0,
      totalRt: 0
    },
    gonogo: {
      rounds: 30,
      interval: 1000,
      sequence: [],
      currentIndex: -1,
      timerId: null,
      stepStartedAt: 0,
      active: false,
      responses: new Map(),
      hits: 0,
      misses: 0,
      falseAlarms: 0,
      correctInhibitions: 0,
      goCount: 0,
      noGoCount: 0,
      hitRtTotal: 0,
      durationMs: 0
    },
    antisaccade: {
      rounds: 18,
      sequence: [],
      currentIndex: -1,
      currentStimulus: null,
      timeoutId: null,
      trialStartedAt: 0,
      sessionStart: 0,
      active: false,
      awaitingResponse: false,
      hits: 0,
      wrong: 0,
      misses: 0,
      totalRt: 0
    },
    focus: {
      warmupMs: 18000,
      challengeMs: 30000,
      intensity: "standard",
      active: false,
      phase: "idle",
      startTime: 0,
      phaseStartedAt: 0,
      tickId: null,
      phaseTimeoutId: null,
      distractorIntervalId: null,
      transientTimeoutIds: [],
      waveCount: 0,
      interruptions: 0,
      durationMs: 0
    },
    reaction: {
      status: "idle",
      readyTime: 0,
      timeoutId: null,
      falseStarts: 0,
      lastMs: null,
      active: false,
      rounds: 8,
      completedRounds: 0,
      results: [],
      sessionStart: 0
    },
    sustained: {
      rounds: 72,
      interval: 900,
      poolSize: 1,
      customLetters: "X",
      sequence: [],
      targetLetters: [],
      currentIndex: -1,
      currentStimulus: null,
      stepStartedAt: 0,
      timeoutId: null,
      active: false,
      responses: new Map(),
      hits: 0,
      misses: 0,
      falseAlarms: 0,
      correctSkips: 0,
      totalRt: 0,
      sessionStart: 0
    },
    breath: {
      cycles: 6,
      beatMs: 1000,
      inhaleBeats: 4,
      exhaleBeats: 6,
      cueMode: "audio",
      active: false,
      phase: "idle",
      cycleIndex: 0,
      beatInCycle: -1,
      totalBeatIndex: -1,
      startTime: 0,
      expectedAt: 0,
      timeoutId: null,
      currentBeatResponse: null,
      hits: 0,
      misses: 0,
      offBeats: 0,
      totalAbsDelta: 0,
      lastDeltaMs: null,
      completedCycles: 0,
      durationMs: 0,
      cycleBeatStates: []
    },
    ui: {
      activePanelId: "home-card"
    }
  };

export const $ = (id) => document.getElementById(id);

export const refs = {
    sidebarToggle: $("sidebar-toggle-btn"),
    sidebarScrim: $("sidebar-scrim"),
    sideRail: $("side-rail"),
    sideRailClose: $("side-rail-close-btn"),
    sideRailCollapse: $("side-rail-collapse-btn"),

    totalSessions: $("total-sessions"),
    totalDuration: $("total-duration"),
    bestSchulte: $("best-schulte"),
    bestTBack: $("best-tback"),
    historyList: $("history-list"),

    schulteSize: $("schulte-size"),
    schulteShowSelected: $("schulte-show-selected"),
    schulteOverview: $("schulte-overview"),
    schulteStartBtn: $("schulte-start-btn"),
    schulteResetBtn: $("schulte-reset-btn"),
    schulteTarget: $("schulte-target"),
    schulteTimer: $("schulte-timer"),
    schulteProgress: $("schulte-progress"),
    schulteStatus: $("schulte-status"),
    schulteBoard: $("schulte-board"),

    tbackLevel: $("tback-level"),
    tbackRounds: $("tback-rounds"),
    tbackInterval: $("tback-interval"),
    tbackStartBtn: $("tback-start-btn"),
    tbackMatchBtn: $("tback-match-btn"),
    tbackSymbol: $("tback-symbol"),
    tbackHint: $("tback-hint"),
    tbackProgress: $("tback-progress"),
    tbackStep: $("tback-step"),
    tbackAccuracy: $("tback-accuracy"),
    tbackFalse: $("tback-false"),
    tbackStatus: $("tback-status"),

    stroopRounds: $("stroop-rounds"),
    stroopStartBtn: $("stroop-start-btn"),
    stroopDisplay: $("stroop-display"),
    stroopWord: $("stroop-word"),
    stroopHint: $("stroop-hint"),
    stroopOptions: $("stroop-options"),
    stroopStep: $("stroop-step"),
    stroopAccuracy: $("stroop-accuracy"),
    stroopAvgRt: $("stroop-avg-rt"),
    stroopProgress: $("stroop-progress"),
    stroopStatus: $("stroop-status"),

    gonogoRounds: $("gonogo-rounds"),
    gonogoInterval: $("gonogo-interval"),
    gonogoStartBtn: $("gonogo-start-btn"),
    gonogoActBtn: $("gonogo-act-btn"),
    gonogoDisplay: $("gonogo-display"),
    gonogoSymbol: $("gonogo-symbol"),
    gonogoHint: $("gonogo-hint"),
    gonogoStep: $("gonogo-step"),
    gonogoAccuracy: $("gonogo-accuracy"),
    gonogoInhibition: $("gonogo-inhibition"),
    gonogoProgress: $("gonogo-progress"),
    gonogoStatus: $("gonogo-status"),

    antisaccadeRounds: $("antisaccade-rounds"),
    antisaccadeStartBtn: $("antisaccade-start-btn"),
    antisaccadeLeftBtn: $("antisaccade-left-btn"),
    antisaccadeRightBtn: $("antisaccade-right-btn"),
    antisaccadeCenterNode: $("antisaccade-center-node"),
    antisaccadeLeftSymbol: $("antisaccade-left-symbol"),
    antisaccadeCenterSymbol: $("antisaccade-center-symbol"),
    antisaccadeRightSymbol: $("antisaccade-right-symbol"),
    antisaccadeHint: $("antisaccade-hint"),
    antisaccadeStep: $("antisaccade-step"),
    antisaccadeAccuracy: $("antisaccade-accuracy"),
    antisaccadeAvg: $("antisaccade-avg"),
    antisaccadeProgress: $("antisaccade-progress"),
    antisaccadeStatus: $("antisaccade-status"),

    focusWarmup: $("focus-warmup"),
    focusChallenge: $("focus-challenge"),
    focusIntensity: $("focus-intensity"),
    focusStartBtn: $("focus-start-btn"),
    focusStopBtn: $("focus-stop-btn"),
    focusFullscreenBtn: $("focus-fullscreen-btn"),
    focusFullscreenExitBtn: $("focus-fullscreen-exit-btn"),
    focusStage: $("focus-stage"),
    focusArena: $("focus-arena"),
    focusTroxlerGridShell: $("focus-troxler-grid-shell"),
    focusTroxlerGrid: $("focus-troxler-grid"),
    focusTroxlerTriangle: $("focus-troxler-triangle"),
    focusDistractorLayer: $("focus-distractor-layer"),
    focusCaption: $("focus-caption"),
    focusHint: $("focus-hint"),
    focusPhase: $("focus-phase"),
    focusCountdown: $("focus-countdown"),
    focusWaves: $("focus-waves"),
    focusBreaks: $("focus-breaks"),
    focusProgress: $("focus-progress"),
    focusStatus: $("focus-status"),

    reactionRounds: $("reaction-rounds"),
    reactionStartBtn: $("reaction-start-btn"),
    reactionZone: $("reaction-zone"),
    reactionTitle: $("reaction-title"),
    reactionText: $("reaction-text"),
    reactionStep: $("reaction-step"),
    reactionLast: $("reaction-last"),
    reactionAvg: $("reaction-avg"),
    reactionBest: $("reaction-best"),
    reactionFalseCount: $("reaction-false-count"),
    reactionStatus: $("reaction-status"),

    sustainedRounds: $("sustained-rounds"),
    sustainedInterval: $("sustained-interval"),
    sustainedPoolSize: $("sustained-pool-size"),
    sustainedLetters: $("sustained-letters"),
    sustainedPool: $("sustained-pool"),
    sustainedRuleSummary: $("sustained-rule-summary"),
    sustainedStartBtn: $("sustained-start-btn"),
    sustainedZone: $("sustained-zone"),
    sustainedStimulus: $("sustained-stimulus"),
    sustainedText: $("sustained-text"),
    sustainedProgress: $("sustained-progress"),
    sustainedStep: $("sustained-step"),
    sustainedAccuracy: $("sustained-accuracy"),
    sustainedAvgRt: $("sustained-avg-rt"),
    sustainedMisses: $("sustained-misses"),
    sustainedFalse: $("sustained-false"),
    sustainedStatus: $("sustained-status"),

    breathCycles: $("breath-cycles"),
    breathCueMode: $("breath-cue-mode"),
    breathStartBtn: $("breath-start-btn"),
    breathStopBtn: $("breath-stop-btn"),
    breathZone: $("breath-zone"),
    breathOrb: $("breath-orb"),
    breathWord: $("breath-word"),
    breathTrack: $("breath-track"),
    breathSubtext: $("breath-subtext"),
    breathPhase: $("breath-phase"),
    breathBeat: $("breath-beat"),
    breathCyclesDone: $("breath-cycles-done"),
    breathAccuracy: $("breath-accuracy"),
    breathAvgDelta: $("breath-avg-delta"),
    breathErrors: $("breath-errors"),
    breathProgress: $("breath-progress"),
    breathStatus: $("breath-status"),

    exportBtn: $("export-records-btn"),
    importBtn: $("import-records-btn"),
    clearBtn: $("clear-records-btn")
  };
